name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '10 6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: 'This PR is stale because it has been open 0 days with no activity. Remove stale label or comment or this will be closed in 1 days.'
          close-pr-message: 'This PR was closed because it has been stalled for  days with no activity.'
          days-before-pr-stale: 0
          days-before-pr-close: 1
          days-before-issue-stale: -1
          days-before-issue-close: -1
